### ISSUE TITLE
feat: add Authorization: Bearer {token} to swagger

### ISSUE THREAD

**Issue by ivica3730k** [SpatialDays/stac-portal-backend#19]
https://github.com/swagger-api/swagger-js/issues/1416

With the auth decorators in place, swagger does not work as it does not send the contents of ./.auth/me ["id_token"] in the header
parameter. 

Maybe it is possible to intercept requests coming out just like we did on https://github.com/SpatialDays/stac-browser/pull/1

![image](https://github.com/SpatialDays/stac-portal-backend/assets/17437897/db6b07a3-c387-4a33-be61-4c8d764abb7a)

**Comment by james-hinton** [comment]
I'll look into this later or tomorrow. 

There's authentication you can do with Swagger, so I can try set something up. https://swagger.io/docs/specification/authentication/

**Comment by james-hinton** [comment]
It seems the best workaround is to set up a separate Swagger UI 3.x that we host ourselves, apart from the one built into Flask-RestX. This new Swagger UI would handle the OAuth2 flow with Azure AD, including the token retrieval and refresh. I think for now, we can just give them a Postman file if they want to do this.

**Comment by ivica3730k** [comment]
@james-hinton 
I would say let's not bother and leave the current swagger as read-only? Can we make it something like that. I don't feel like making a postman collection if we are already half way there

**Comment by james-hinton** [comment]
> @james-hinton 
> 
> I would say let's not bother and leave the current swagger as read-only? Can we make it something like that. I don't feel like making a postman collection if we are already half way there

Sure, it won't be usable though. But for documentation it's A+

**Comment by ivica3730k** [comment]
Still makes you write that annoying dto. Let's explore the options of keeping it read-only on Monday. If not, we can remove it altogether/

**Comment by ivica3730k** [comment]
#wontfix
